spring:
  flyway:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://postgres.c1isl1idqzxk.us-east-1.rds.amazonaws.com/postgres:5432/postgres"
    user: ${USERNAME}
    password: ${PASSWORD}
    enabled: true
  datasource:
    url: jdbc:postgresql://postgres.c1isl1idqzxk.us-east-1.rds.amazonaws.com/postgres:5432/postgres
    username: ${USERNAME}
    password: ${PASSWORD}
