spring:
  flyway:
    driverClassName: org.postgresql.Driver
    url: "postgres.c1isl1idqzxk.us-east-1.rds.amazonaws.com/postgres"
    user: ${USERNAME}
    password: ${PASSWORD}
    enabled: true
  datasource:
    url: postgres.c1isl1idqzxk.us-east-1.rds.amazonaws.com/postgres
    username: ${USERNAME}
    password: ${PASSWORD}
