name: service-deployment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install aws cli
        run: sudo apt-get update && sudo apt-get install -y awscli

      - name: Set up AWS credentials
        run: |
          mkdir -p ~/.aws
          touch ~/.aws/credentials
          echo "[default]
          aws_access_key_id = ${AWS_ACCESS_KEY_ID}
          aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" > ~/.aws/credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Delete a repository named demo-repository
        run: aws ecr delete-repository --repository-name demo-repository --force --region us-east-1

      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v1

      - name: Copy Lock File to Local
        run: cd ./deployment/basic && aws s3 cp s3://tgsbucket/backup/terraform.tfstate . && aws s3 cp s3://tgsbucket/backup/terraform.tfstate.backup .

      - name: "Format terraform"
        run: cd ./deployment/basic && terraform fmt

      - name: "Initialize terraform"
        run: cd ./deployment/basic && terraform init

      - name: "Validate terraform"
        run: cd ./deployment/basic && terraform validate

      - name: "Run terraform apply"
        run: cd ./deployment/basic && terraform destroy -auto-approve

      - name: Remove S3 Bucket
        run: aws s3 rb s3://yysBucket



